server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Go service logs
  - job_name: go-training-system
    static_configs:
      - targets:
          - localhost
        labels:
          job: go-training-system
          service: go-backend
          __path__: /var/log/app/go-service/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
            trace_id: trace_id
            span_id: span_id
            method: method
            path: path
            status: status
            duration: duration
      - labels:
          level:
          method:
          status:
      - timestamp:
          source: timestamp
          format: RFC3339

  # Node.js service logs
  - job_name: user-service-nodejs
    static_configs:
      - targets:
          - localhost
        labels:
          job: user-service
          service: nodejs-backend
          __path__: /var/log/app/user-service/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            trace_id: traceId
            method: method
            url: url
            status: status
            duration: duration
      - labels:
          level:
          service:
          method:
          status:
      - timestamp:
          source: timestamp
          format: RFC3339

  # Docker container logs
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
    pipeline_stages:
      - docker: {}
      - labels:
          container_name:
          stream:
